.PHONY: clean All

All:
	@echo "----------Building project:[ FavouriteNumber - Release ]----------"
	@cd "FavouriteNumber" && "$(MAKE)" -f  "FavouriteNumber.mk"
clean:
	@echo "----------Cleaning project:[ FavouriteNumber - Release ]----------"
	@cd "FavouriteNumber" && "$(MAKE)" -f  "FavouriteNumber.mk" clean
